### ISSUE TITLE
Crash at end of list

### ISSUE THREAD

**Issue by SeraphSephiroth** [devnoname120/vhbb#47] opened 2018-08-29 13:54 UTC
App crashes when reaching the end of a list

https://youtu.be/JyJUQ9LOiGw <--- Video

[psp2core-1535550237-0x0000742155-eboot.bin.psp2dmp.zip](https://github.com/devnoname120/vhbb/files/2332370/psp2core-1535550237-0x0000742155-eboot.bin.psp2dmp.zip)

**Comment by devnoname120** [comment] 2018-09-01 15:12
I cannot reproduce your issue here, but according to your coredump, it crashes in `SceGxm`.

Could you try with this [VHBB debug build](https://github.com/devnoname120/vhbb/files/2342467/vhbb_debug.vpk.zip) and report back?

**Comment by SeraphSephiroth** [comment] 2018-09-15 15:45
Sorry about the delay. Looks like your new build fixes the issue.

**Comment by RY0M43CH1Z3N** [comment] 2018-09-15 17:45
@SeraphSephiroth Then, close the issue.

**Closed** 2018-09-15 18:02 UTC
Labels: crash
