### ISSUE TITLE
NetworkError: The requested URL returned error: 404 Not Found" [/__w/1/s/src/font.cpp:97 Font::FitString()]  FitString: "Couldn't check for update

### ISSUE THREAD

**Issue by rigo098** [devnoname120/vhbb#117] opened 2022-11-22 22:06 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log file**

VHBB started.
- Version: 00.92
- Commit: fc901d6520a7802d2af0d51da731fd530108db43
- GitHub: https://github.com/devnoname120/vhbb/tree/fc901d6520a7802d2af0d51da731fd530108db43
- OS: 3.60

[/__w/1/s/src/vitaPackage.cpp:216 VitaPackage::VitaPackage()]  Loading PAF
[/__w/1/s/src/vitaPackage.cpp:230 VitaPackage::~VitaPackage()]  Unloading PAF
[/__w/1/s/src/network.cpp:259 Network::TestConnection()]  Content length: 8
[/__w/1/s/src/update.cpp:103 Update::getVersionInfo()]  sceIoRemove(ux0:/data/VitaHbBrowser/latest_version.yml) = 0x00000000
[/__w/1/s/src/network.cpp:125 Network::Download()]  Downloading https://vhbb.download/version.php to ux0:/data/VitaHbBrowser/latest_version.yml
[/__w/1/s/src/network.cpp:204 Network::Download()]  cURLpp exception: The requested URL returned error: 404 Not Found https://vhbb.download/version.php 
[/__w/1/s/src/update.cpp:110 Update::getVersionInfo()]  Couldn't download version.yml: NetworkError: The requested URL returned error: 404 Not Found
[/__w/1/s/src/Views/dialogView.cpp:45 DialogView::DialogView()]  DialogView::DialogView()
[/__w/1/s/src/Views/dialogView.cpp:65 DialogView::prepare()]  Created DialogView "Couldn't check for update

NetworkError: The requested URL returned error: 404 Not Found"
[/__w/1/s/src/font.cpp:97 Font::FitString()]  FitString: "Couldn't check for update

NetworkError: The requested URL returned error: 404 Not Found", 602
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "check" fits: 182
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "for" fits: 225
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "update

NetworkError:" fits: 319
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "The" fits: 319
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "requested" fits: 357
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "URL" fits: 414
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "returned" fits: 529
[/__w/1/s/src/font.cpp:117 Font::FitString()]  "error:" overflows: 604
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "404" fits: 529
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "Not" fits: 529
[/__w/1/s/src/font.cpp:112 Font::FitString()]  "Found" fits: 529
[/__w/1/s/src/font.cpp:122 Font::FitString()]  Fitted string: "Couldn't check for update

NetworkError: The requested URL returned
error: 404 Not Found"
[/__w/1/s/src/network.cpp:125 Network::Download()]  Downloading https://rinnegatamante.it/vitadb/list_hbs_yaml.php to ux0:/data/VitaHbBrowser/homebrews.yaml
[/__w/1/s/src/network.cpp:211 Network::Download()]  Done downloading https://rinnegatamante.it/vitadb/list_hbs_yaml.php
[/__w/1/s/src/input.cpp:263 Input::TouchInRectangle()]  TouchInRectangle rectangle: 324.000000,422.000000:636.000000,468.000000
[/__w/1/s/src/input.cpp:266 Input::TouchInRectangle()]  TouchInRectangle touch: 421.219385,433.898804
[/__w/1/s/src/shapes.cpp:13 Rectangle::Inside()]  Inside point: 421.219385,433.898804
[/__w/1/s/src/input.cpp:263 Input::TouchInRectangle()]  TouchInRectangle rectangle: 324.000000,422.000000:636.000000,468.000000
[/__w/1/s/src/input.cpp:266 Input::TouchInRectangle()]  TouchInRectangle touch: 422.219906,432.897884
[/__w/1/s/src/shapes.cpp:13 Rectangle::Inside()]  Inside point: 422.219906,432.897884
[/__w/1/s/src/input.cpp:263 Input::TouchInRectangle()]  TouchInRectangle rectangle: 324.000000,422.000000:636.000000,468.000000
[/__w/1/s/src/input.cpp:266 Input::TouchInRectangle()]  TouchInRectangle touch: 445.732152,473.435143
[/__w/1/s/src/shapes.cpp:13 Rectangle::Inside()]  Inside point: 445.732152,473.435143
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/f80b48d9880373930c5349ac5104a072add87c6c99f0a62e6f9b24717b333da8.png
[/__w/1/s/src/input.cpp:263 Input::TouchInRectangle()]  TouchInRectangle rectangle: 324.000000,422.000000:636.000000,468.000000
[/__w/1/s/src/input.cpp:266 Input::TouchInRectangle()]  TouchInRectangle touch: 421.219385,471.933763
[/__w/1/s/src/shapes.cpp:13 Rectangle::Inside()]  Inside point: 421.219385,471.933763
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/f1464d52eb0d6b26677f497f2e4a387d20793e3eaeee6867810d8f114ba0c64a.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/f53708caff5294940ab1693d99e59ca90236b3c8feba058bc72f5c2f649e9ac0.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fa424ba84a457cc11cd873d02cc404d0391f532ad0014835957dd498363aea98.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fbc2b511434e020c0fec928113a15dbf6653e923457581ab21f3aed644769ec4.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fcf258922f702bebaeca657dbeac153377c1716326fdeb9fce2ce7c369d0bcf0.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fe063a9f4005b2dd72674fda39e689cf111e52e2ce7821e0754c4830669f5abb.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fe188b56869589b36f104ddfe6d05f5a9b76d3b40739641edaf21e697247b95b.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/fed314676a182bf702355bf0a46e6366933a92c9dceb8bec0504f21a034fbeda.png
[/__w/1/s/src/zip.cpp:122 Zipfile::Unzip()]  file:ux0:/data/VitaHbBrowser/icons/labyrinth.png

**Comment by robsdedude** [comment] 2022-11-23 08:19
Duplicate of https://github.com/devnoname120/vhbb/issues/115

**Closed as not planned by robsdedude** 2022-11-23 08:19 UTC

**Comment by pipechavescr** [comment] 2023-05-13 19:17
Which is the fix, I have the issue

**Comment by robsdedude** [comment] 2023-05-15 09:03
@pipechavescr I'm afraid there is no fix yet :/
