### ISSUE TITLE
Crash on launch, network request doesn't work

### ISSUE THREAD

**Issue by Codeman785** [devnoname120/vhbb#53] opened 2018-11-04 20:48 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Log file**

[VHBB_2018-11-04_13-45-36.log](https://github.com/devnoname120/vhbb/files/2546287/VHBB_2018-11-04_13-45-36.log)

**Comment by devnoname120** [comment] 2018-11-04 21:03
Can you try to go to the following URL using Vita's browser? You should see some text if it works.
https://rinnegatamante.it/vitadb/list_hbs_yaml.php

**Comment by Codeman785** [comment] 2018-11-07 00:04
It takes me to what appears to be a text version of vhhb

**Comment by devnoname120** [comment] 2018-11-08 15:10
Seems to be a duplicate of https://github.com/devnoname120/vhbb/issues/40.

**Closed** 2018-12-30 17:13 UTC
Labels: crash
