### ISSUE TITLE
Crash when navigating to Utilities -> Custom Theme Manager

### ISSUE THREAD

**Issue by AnotherMuggle** [devnoname120/vhbb#46] opened 2018-08-15 21:53 UTC
I can happily browse the vhbb with no issues but as soon as I open Custom Theme Manager to read its description my Via crsahes with a message about a GPU crash.  This crash can be reproduced every time and it causes the Vita to shutdown. I am using version 0.81 on firmware 3.65 with enso.

**Comment by devnoname120** [comment] 2018-08-16 18:50
Strange, it seems to work here.

Could you try to delete the following folder and report back?
```
ux0:/data/VitaHbBrowser
```

**Comment by AnotherMuggle** [comment] 2018-08-16 19:04
Deleted the folder and tried again. Everything works fine but as soon as I opened Custom Theme Manager the Vita has froze on that screen. PS button is still blue but doesn't do a thing and only holding the power button does anything... That is the screen goes black and the PS button flashes blue for quite a while before powering off. This actually happened previously and after a reboot it will do the crash and show the GPU crash message.

**Comment by devnoname120** [comment] 2018-08-16 20:06
Maybe it's already fixed in the code base, I will let you know when I do a new release.

https://github.com/devnoname120/vhbb/issues/30

**Comment by devnoname120** [comment] 2018-11-03 17:36
Can you try with the latest release?
https://github.com/devnoname120/vhbb/releases

**Comment by AnotherMuggle** [comment] 2018-11-04 16:08
I got quite interesting results. Initially the problem seemed the
same...that is all content displays fine except for Custom Theme Manager,
which causes a crash.  I then noticed the new option to write debug logs,
so I tried it.  The interesting thing is it NEVER crashes when launching
with this option.  I tried multiple times with and without logging enabled
and not once did it crash with logging enabled but it crashed every time
when launched normally.

The crash seems to happen one of two ways, either the screen freezes but
the Vita sounds like its responding to button presses, despite the screen
not freshing OR I immediately get a black GPU Crash Screen.  In both cases
I have to hold the power button to force a reboot.

Cheers,
Tom

**Comment by devnoname120** [comment] 2018-11-04 17:03
This is very strange and it sounds like a concurrency issue...
Could you provide a log here? We never know, I might see something strange in it...

**Comment by devnoname120** [comment] 2018-11-16 17:17
Sure, it should be useful!
Make sure to get a crash dump from the latest version.

**Comment by Vantuz** [comment] 2018-12-15 15:38
Can reproduce on vhbb 0.83 and 3.68 firmware. The same also happens with ScummVM Buildbot.

**Comment by devnoname120** [comment] 2018-12-16 12:40
@Vantuz Could you provide me with some logs and a crash dump?

**Comment by devnoname120** [comment] 2019-03-04 07:21
Cannot reproduce and nobody provided logs.

**Closed by devnoname120** 2019-03-04 07:21 UTC
Labels: crash

**Comment by Vantuz** [comment] 2019-03-04 12:13
@devnoname120 sorry, I forgot about this :( Can you provide me with some guidance on how to extract crash dump/debug logs from Vita? Also, as in @AnotherMuggle's case, it never crashes when launching with "write debug logs" option.
