### ISSUE TITLE
when i open vhbb error C2-12828-1 

### ISSUE THREAD

**Issue by 0xakrem** [devnoname120/vhbb#15] opened 2017-05-01 11:15 UTC
when i open vhbb error C2-12828-1

**Comment by ArkSource** [comment] 2017-05-01 12:31
@0xakrem 
is C2-12828-1 only occurring for VHBB or other applications as well?
First restart your system, and let me know if the error persists ?

**Comment by 0xakrem** [comment] 2017-05-01 21:26
i did and clean cookies etc the same :( 
i've 3,60 with henkaku

**Comment by szczuru** [comment] 2017-05-01 21:47
Same here :(

**Comment by ArkSource** [comment] 2017-05-02 01:34
@0xakrem  @szczuru 
If a system restart didn't do the trick, rebuild your database.
steps if needed:
- power down your Vita
- hold down the R button and PS button and turn on your Vita.
- keep holding R button and PS button until the 'Safe Mode' menu appears.
- select the 'Rebuild Database' option (option 2 i think it is).
- wait for the vita to boot.
- apply HENkaku and try loading a hb application.

**Comment by szczuru** [comment] 2017-05-02 11:51
Still same error :(
Maybe psp2core dumped during error will help, here's mine:
http://www44.zippyshare.com/v/G2TY1jIB/file.html

**Comment by ArkSource** [comment] 2017-05-02 12:30
Unfortunately not, C2-12828-1 will be HENkaku related not VHBB.
You do have safe mode turned off right?
VHBB will only run in unsafe mode as it requires additional access for some of it's procedures. 
You can set this via molecular shell.

**Comment by 0xakrem** [comment] 2017-05-02 15:06
its working thanks !

**Comment by szczuru** [comment] 2017-05-02 16:06
I have disabled safe mode :(

**Comment by 0xakrem** [comment] 2017-05-02 16:32
yes, C2-12828-1 is HENkaku related not VHBB.
You do have safe mode turned off right?
VHBB will only run in unsafe mode as it requires additional access for some of it's procedures.
You can set this via molecular shell.
and try reboot and do HENkaku again

**Comment by CelesteBlue-dev** [comment] 2017-05-02 16:33
@szczuru Delete the ux0:tai folder then reboot.

**Comment by szczuru** [comment] 2017-05-03 11:33
@0xakrem @CelesteBlue-dev Deleted tai folder and even reinstalled whole TaiHEN (by pressing R during install) - still same error :(

**Comment by CelesteBlue-dev** [comment] 2017-05-03 11:39
@szczuru Now delete ux0:data/vhbb/.

**Comment by szczuru** [comment] 2017-05-03 11:44
Works! :D Thanks a lot!

**Comment by CelesteBlue-dev** [comment] 2017-05-03 13:03
So to conclude there are 3 causes of the Error C2-128128-1 in VHBB and for each a solution : 
- if UNSAFE MODE is not enable in MolecularShell : enable it.
- if ux0:tai/config.txt launches with *all an uncompatible plugin : delete the bad lines or delete ux0:tai/config.txt.
- if ux0:data/vhbb/ is corrupted : delete ux0:data/vhbb/.

We can't know which is the cause between these 3, so you need to apply the 3 fixes.

@devnoname120 @ArkSource You should add these solutions into the README.
@devnoname120 @ArkSource Issues resolved. You can close it.

**Comment by ArkSource** [comment] 2017-05-07 04:24
Might link to a write up on the VitaSDK forum for 'Error C2-128128-1' as the initial error is not directly related to VHBB.
I'll also add a link to the README.
Cheers.

**Closed by ArkSource** 2017-05-07 04:24 UTC

**Comment by erumaithi** [comment] 2019-06-17 05:15
I have to add one more solution to the above that worked for me. i have faced the same issue and non of the solution above worked.

- If you have the old Vita with Cell network , install any SIM card then go the setting menu under Network and disable the mobile network by unchecking the box. this option only appear with sim installed. then the app will use the wifi for internet. 

weird but worked for me.

**Comment by devnoname120** [comment] 2019-06-17 11:20
@erumaithi Interesting, were other apps able to access the Internet anyway?

**Comment by DraxDauragon** [comment] 2021-11-13 08:03
Hey if anyone is still patrolling this thread i'm having issues and could use a hand. VHBB would crash before getting to the white Gekhen screen. I rebuilt the Database, Unsafe is checked in HENkaku, and deleted the tai and VHBB folders.  It now crashes post Gekhen screen when there isn't a VHBB folder. I keep deleting the VHBB folder and have tried to rebuild the Database when there isn't a VHBB folder with no luck.
