### ISSUE TITLE
Error C-12828-1 on startup...Again.

### ISSUE THREAD

**Issue by AleScanu** [devnoname120/vhbb#29] opened 2018-01-01 23:33 UTC
I'm sorry open another issue for this error, but every solutions I've tried with the previous issues doesn't work. I have formatted PS Vita, Memory Card, rebuilt database, deleted ux0:tai/config.txt, delete ux0:data/vhbb, reinstalled the whole henkaku plus enso...Nothing work. I don't know what to do, can anyone tell me what happened? I have installed vhbb v0.81 with both VitaShell and MolecularShell (last version) and run it in unsafe mode...Nothing. And I've tried to deactivate and reactivate my PS Vita twice.

**Comment by devnoname120** [comment] 2018-01-01 23:36
Duplicate of https://github.com/devnoname120/vhbb/issues/28.

**Closed by devnoname120** 2018-01-01 23:36 UTC
Labels: duplicate
